language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo run --example create_from_str_array
  - cargo doc
env:
  - FEATURES=
  - FEATURES=resolve_file_uris
  - FEATURES=resolve_http_uris
  - FEATURES=resolve_file_uris resolve_http_uris
